AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Currency Converter API'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name
  S3Bucket:
    Type: String
    Description: S3 bucket containing the Lambda function deployment package
  S3Key:
    Type: String
    Description: S3 key for the Lambda function deployment package
    
Resources:
  # Lambda Function
  CurrencyConverterFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub currency-converter-${Environment}
      Runtime: python3.13
      Handler: app.main.handler
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      Role: !GetAtt LambdaExecutionRole.Arn

  # Lambda Function URL
  CurrencyConverterFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt CurrencyConverterFunction.Arn

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # CloudWatch Alarms
  ApiLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Environment}-currency-converter-latency
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref CurrencyConverterFunction

  ErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Environment}-currency-converter-errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref CurrencyConverterFunction

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !GetAtt CurrencyConverterFunctionUrl.FunctionUrl